# netlify.toml

[build]
  command = "npm run build"  
  functions = "netlify/functions"  
  publish = "public"  

[[redirects]]
  
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  
  for = "/src/views/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"